export const fallback = {
  HEARTBEAT_SERVER_BASE_URL: 'http://localhost:3000',
  HEARTBEAT_CLIENT_INTERVAL: 10,
  HEARTBEAT_CLIENT_ID: 'undefined',
  HEARTBEAT_CLIENT_DATE_FORMAT: 'YYYY-MM-DD HH:mm:ss:SSS Z',
};
